# Use root/example as user/password credentials
version: '3.3'

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_USER: appuser
      MYSQL_PASSWORD: test123
    ports:
      - '4001:3306'
    expose:
      - '3306'
    volumes:
      - ./docker-config/db-init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080